### PR TITLE
fix parse error for PolyOverZ from_str

### LINKED ISSUE #183: fix error in PolyOverZ

### PR DESCRIPTION
**Pull request by Marvin-Beckmann**
This closes #183.

The problem: fmpz_poly_set_str ignores both symbols after the number of coefficients, this is now fixed with a dedicated string. This issue does not occur for PolyOverQ. I added according tests in the from-methods

### CODE REVIEW

File: src/integer/poly_over_z/from.rs [hunk 1]
```diff
@@ -52,18 +52,30 @@ impl FromStr for PolyOverZ {
...
+
+        if s_trimmed == "0" {
+            return Ok(Self::default());
+        }
+
+        // fmpz_poly_set_str just skips the two symbols after the number of
+        // coefficients (even if they are not whitespaces), hence we have to check if
+        // they are whitespaces manually.
+        // and we only have to check it once, because for every other position it checks
+        // whether there is only one whitespace
```
Comment (MoogSven) [inline src/integer/poly_over_z/from.rs:66]: It ensures that the first character behind the first number is a space.
Interesting Sitenote: whitespaces that are not spaces can be included within numbers, e.g. `\n`, `\t` and will be ignored.

```rust
let a = PolyOverZ::from_str("2  1\n2 3").unwrap();
let b = PolyOverZ::from_str("2  12 3").unwrap();
assert_eq!(a,b);
```

```suggestion
        // fmpz_poly_set_str just skips the two symbols after the first space
        // behind the number of coefficients (even if not a space), hence
        // it has to be checked here to ensure that no number is lost.
        // We only have to check it once, because for every other position it checks
        // whether there is only one space.
```

File: src/integer/poly_over_z/from.rs [hunk 2]
```diff
@@ -52,18 +52,30 @@ impl FromStr for PolyOverZ {
     /// [`InvalidStringToCStringInput`](MathError::InvalidStringToCStringInput)
     /// if the provided string contains a Null Byte.
     fn from_str(s: &str) -> Result<Self, Self::Err> {
+        // remove whitespaces at the start and at the end
+        let s_trimmed = s.trim();
```
[the remark this answers is not in the document]
Comment (Marvin-Beckmann) [reply src/integer/poly_over_z/from.rs:58]: done

File: src/integer/poly_over_z/from.rs (hunk 1 above)
Comment (Marvin-Beckmann) [reply src/integer/poly_over_z/from.rs]: interesting, I added your suggestion, do you want me to also include this sitenote?

File: src/rational/poly_over_q/from.rs
[the remark this answers is not in the document]
Comment (Marvin-Beckmann) [reply src/rational/poly_over_q/from.rs:1]: done

File: src/integer/poly_over_z/from.rs (hunk 1 above)
Comment (MoogSven) [reply src/integer/poly_over_z/from.rs]: No, just the suggestion is enough. The other thing is just something interesting to know that I stumbled over during the review.

**Review by MoogSven — APPROVED** [review]
Looks Good :+1:
